# Generated by Django 4.1.2 on 2022-10-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_library',
            name='release_date',
            field=models.DateField(max_length=255),
        ),
    ]
